name: Trigger ORNL CI/CD Pipeline
on: 
  push:
    branches:
      - main
jobs:
  ornl-trigger:
    runs-on: ubuntu-20.04
    steps:
      - run: curl -X POST -F token=$TOKEN -F ref=$REF $URL 
        env:
          TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          REF: master
          URL: ${{ secrets.GITLAB_TRIGGER_URL }}
